name: Test-workflow-stuff
run-name: Actions testing
on: workflow_dispatch
jobs:
  test-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      run: |
        MARKETING_VERSION=$(grep -m1 'MARKETING_VERSION =' MyApp.xcodeproj/project.pbxproj \
          | sed 's/.*MARKETING_VERSION = \(.*\);/\1/')

        BUILD_NUMBER=$(grep -m1 'CURRENT_PROJECT_VERSION =' MyApp.xcodeproj/project.pbxproj \
          | sed 's/.*CURRENT_PROJECT_VERSION = \(.*\);/\1/')

        echo "MARKETING_VERSION=$MARKETING_VERSION" >> "$GITHUB_ENV"
        echo "BUILD_NUMBER=$BUILD_NUMBER" >> "$GITHUB_ENV"
