name: Test-workflow-stuff
run-name: Actions testing
on: workflow_dispatch
jobs:
  test-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          MARKETING_VERSION=$(grep -m1 'MARKETING_VERSION =' JESSI.xcodeproj/project.pbxproj \
            | sed 's/.*MARKETING_VERSION = \(.*\);/\1/')

          BUILD_NUMBER=$(grep -m1 'CURRENT_PROJECT_VERSION =' JESSI.xcodeproj/project.pbxproj \
            | sed 's/.*CURRENT_PROJECT_VERSION = \(.*\);/\1/')
      - run: |
          echo "Version: $MARKETING_VERSION"
          echo "Build: $BUILD_NUMBER"
