name: Update JESSI Source
run-name: Update JESSI Source
on:
  workflow_dispatch:
  release:
    types: published
jobs:
  test-command:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      
      - name: Make all source modifications in one line lol
        run: curl -L -s https://github.com/${{ github.repository }}/releases/download/source/source.json | jq --arg version $(grep -m1 'MARKETING_VERSION =' JESSI.xcodeproj/project.pbxproj | sed 's/.*MARKETING_VERSION = \(.*\);/\1/') --arg date $(date -I) --arg size $(curl -L -s https://github.com/${{ github.repository }}/releases/latest/download/JESSI.ipa | wc -c) '.apps[].versions[].version = $version | .apps.[].versions[].date = $date | .apps[].versions[].size = ($size | tonumber)' > source.json

      - name: Update source release
        uses: ncipollo/release-action@v1.21.0
        with:
          allowUpdates: true
          artifacts: "source.json"
          artifactContentType: JSON
          tag: "source"